# @format
branches:
  only:
    - master

os: linux
dist: focal
language: generic
services:
  - docker

jobs:
  include:
    - stage: Building and running the container
      script:
        - docker build -t vcity:webdoc .
        - docker run --rm --detach -t vcity:webdoc
        - travis_wait 2
        - docker stop $(docker ps -a -q --filter ancestor=vcity:webdoc --format="{{.ID}}")

